apiVersion: apps/v1
 kind: Deployment
 metadata:
 name: my-node-app
 spec:
 replicas: 2 # Run 2 instances
 selector:
 matchLabels:
 app: my-node-app
 template:
 metadata:
 labels:
 app: my-node-app
 spec:
 containers:- name: my-node-app
 image: my-node-app:latest
 ports:- containerPort: 8080
 
apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  type: NodePort # Or LoadBalancer on cloud
  selector:
    app: my-node-app
  ports:
    - port: 8080
      targetPort: 8080
